# Deploy the pattern library to gh-pages
dist: trusty
language: node_js
node_js:
  - 12

# branches:
#   except:
#     - /^.visual-framework\/.*$/

stages:
  - deploy

before_script:
  - yarn install
  - yarn global add gulp-cli
  - yar run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: gh-pages
  local-dir: build
  cache:
    paths:
      - node_modules
  on:
    branch:
      - master
