title: VF Bioimaging banner
label: Bioimaging banner
preview: '@preview--elements'
status: beta
variants:
  - name: template
    hidden: true
context:
  component-type: container
  color_foreground: var(--vf-ui-color-white)
  color_background: var(--vf-color-gray-dark)
